Repository thoth-station/solver-project-url-job, pull requests merged in 2021-07, with the labels that each got.

#3 Configure AICoE-CI
  .aicoe-ci.yaml
Labels: approved, lgtm, size/S

#2 added logic for parsing git repo from solver
  Pipfile
  Pipfile.lock
  app.py
Labels: approved, size/XXL

#6 Allow Bjoern to make new versions
  .thoth.yaml
Labels: approved, size/XS

#9 added matching version for thoth-storages in Pipfile.lock
  Pipfile.lock
Labels: approved, size/M

#12 Fix logic to meet desired semantics
  app.py
Labels: approved, size/XS

#14 changed pyproject.toml to contain description and name
  pyproject.toml
Labels: approved, size/XS

#18 Readme update
  README.md
Labels: approved, lgtm, size/S

#20 changed logger debug to warning for invalid Github/Gitlab URL
  app.py
Labels: approved, sig/observability, size/XS

#26 Bug dictionary
  .gitignore
  app.py
Labels: approved, size/S
